name: Deploy

on:
  push:
    branches:
      - master

inputs:
  buildMode:
    description: "Build projects using different modes [default: 'release']"
    required: true
    default: "release"
  toolchain:
    description: "Build projects using a different rust toolchain [default: 'stable']"
    required: true
    default: "stable"
  outDirectory:
    description: "The `out_dir` property configured in Dioxus.toml [default: 'dist']"
    required: true
    default: "dist"
  rootPath:
    description: "Source code root path [default: '.']"
    required: true
    default: "."

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repo
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Dioxus-CLI
        shell: bash
        run: cargo install dioxus-cli

      - name: Build Project ğŸ
        shell: bash
        run: cd ${{ inputs.rootPath }} && dx build --${{ inputs.buildMode }} && cp ./${{ inputs.outDirectory }}/index.html ./${{ inputs.outDirectory }}/404.html

      - name: Deploy Project ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ inputs.rootPath }}/${{ inputs.outDirectory }}
          clean: false
